[package]
name = "rust"
version = "0.1.0"
authors = ["jakeec <jake.ethan.carrington@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contracts = "0.3.0"
rand = "*"